[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
# [tool.hatch.build.targets.wheel]
#       packages = ["src/illuminator"]

[project]
name = "illuminator"
version = "3.1-beta.0"
description = "A development toolkit for simulating energy systems"
license = {file = "LICENSE"}
readme = "readme.md"
requires-python = ">=3.11"
authors = [
    { name = "Jort Groen"},
    { name = "Despoina Kassandra Georgiadi"},
    { name = "Josip Grguric"},
    { name = "Yasel Quintero Lares"},
    { name = "Joan Pijpker"},
    { name = "Manuel Garcia Alvarez"},
    { name = "Mano Rom"},
]
maintainers = [
    { name = "Illuminator Team", email = "illuminator@tudelft.nl"}
    ]
dependencies = [
    "arrow>=1.4.0",
    "lxml>=6.1.1",
    "matplotlib>=3.10.9",
    "paho-mqtt>=2.1.0",
    "pandas>=3.0.3",
    "numpy>=2.3.5",
    "mosaik>=3.6.0",
    "ruamel.yaml>=0.19.1",
    "schema>=0.7.7", 
    "typer>=0.25.1",
    "mpi4py>=4.1.2"
]
keywords = [
    "energy",
    "simulation",
    "development",
    "toolkit"
]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Programming Language :: Python"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "Sphinx",
    "sphinx-rtd-theme",
    "myst-parser",
    "sphinx-copybutton",
    "nbsphinx",
]

[project.scripts]
illuminator = "illuminator.cli.main:app"

[project.urls]
Documentation = "https://illuminator-team.github.io/website/"
Repository = "https://github.com/Illuminator-team/Illuminator.git"
"Bug Tracker" = "https://github.com/Illuminator-team/Illuminator/issues"
Changelog = "https://github.com/Illuminator-team/Illuminator/blob/main/CHANGELOG.md"
