wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.15.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1686737390.952218
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 7
      - 23
      4: 3.8.16
      5: 0.15.3
      8:
      - 3
      - 5
    m:
    - 1: custom_step
      6:
      - 3
