scenario: ExampleScenario # in mosaik so called world
scenario_data: 'path/to/file' #path to the scenario data file ()
start_time: '2012-01-02 00:00:00' # ISO 8601 start time of the simulation
end_time: 10 # duration in seconds 
nodes: # list of node for the grid network t
- name: Battery1 # name for the node
  model: BatteryModel # name of the model registered in the Illuminator
  Inputs: [demand_power_flow=0] 
  Outputs: [effective_power_flow=0, soc=None]
  Parameters: [charge_power_max=100, discharge_power_max=200, soc_min=0.1, soc_max=0.9, capacity=1000]
  States: [initial_soc=0.5]
- name: Battery2
  model: BatteryModel # nodes can reuse the same model
  Inputs: [demand_power_flow=0] 
  Outputs: [effective_power_flow=0, soc=None]
  Parameters: [charge_power_max=100, discharge_power_max=200, soc_min=0.1, soc_max=0.9, capacity=5000]
  States: [initial_soc=0.5]
- name: PV1
  model: PVModel
  Inputs: [demand_power_flow=0] 
  Outputs: [effective_power_flow=0, soc=None]
  Parameters: [charge_power_max=100, discharge_power_max=200, soc_min=0.1, soc_max=0.9, capacity=1000]
  States: [initial_soc=0.5]
connections:
- from: Battery1 # start node
  to: Battery2 # end node
  data: !!pairs # a list values to be exchanged between the nodes. 'pairs' is a YAML keyword
    - val1: val2 # output of 'from node': input of 'to node'
    - val3: val4 
    - val5: val6
- from: PV 
  to: Battery2 
  data: !!pairs # using the generic 'data' keyword to define what it is exchanged between the nodes
    - val1: val2
    - val3: val4
   
     

    


  
  


