name: End-to-End Test on PR to dev

on:
  pull_request:
    branches: [dev]

jobs:
  e2e-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Run end-to-end test
      run: python tests/e2e_test.py

    - name: Compare CSV files
      run: |
        diff tests/outputs/output.csv tests/outputs/expected_output.csv
